"""empty message

Revision ID: 3f9535e18d22
Revises: 626d20572ac9
Create Date: 2021-12-14 14:00:57.187996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9535e18d22'
down_revision = '626d20572ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_in_pounds', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('health_log_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_log_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weight_in_pounds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_username', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], name='health_log_model_user_username_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_log_model_pkey')
    )
    op.drop_table('health')
    # ### end Alembic commands ###
